export default {
  MODELS: {
    USER: 'USER_MODEL',
  },
  CONNECTIONS: {
    MONGODB: 'MONGODB_CONNECTION',
  },
  CONFIGS: {
    DATABASE: 'DATABASE_CONFIG',
    HTTP: 'HTTP_CONFIG',
    AUTH: 'AUTH_CONFIG',
  },
};
